# Generated by Django 5.2.4 on 2025-07-31 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_todo_thumnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='thumnail',
        ),
        migrations.AddField(
            model_name='todo',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='할 일과 관련된 이미지를 업로드하세요.', null=True, upload_to='todo/thumbnails/'),
        ),
    ]
